CREATE DATABASE IF NOT EXISTS career_ai
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'career'@'%' IDENTIFIED BY 'career1234';
GRANT ALL PRIVILEGES ON career_ai.* TO 'career'@'%';
FLUSH PRIVILEGES;

USE career_ai;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(100) NOT NULL,
  career VARCHAR(50) DEFAULT '',
  portfolioUrl VARCHAR(500) DEFAULT '',
  stacks JSON DEFAULT NULL,
  createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_users_email (email)
);
